---

# This Ansible playbook creates infrastructure in AWS according to the given CloudFormation template file.

# To run this playbook:
# ansible-playbook -e "stack_name=FOO" -i localhost, create_queues_and_database.yml

- hosts: all
  connection: local
  vars:
    - template_file: cloudformation-templates/infrastructure-queues-and-sdb.template
    - region: eu-west-1
  tasks:
  - name: Create CloudFormation stack
    action: cloudformation stack_name="aws-workshop-{{ stack_name }}" state=present region={{ region }} disable_rollback=false template="{{ template_file }}"
    args:
      template_parameters:
        StackName: "{{ stack_name }}"
      tags:
        Name: "aws-workshop-{{ stack_name }}"
